spring:
  application:
    name: itoken-service-upload
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084


server:
  port: 9505



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info




