spring:
  application:
    name: itoken-config
    #name: I-LOVE-YOU
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/codercyou/spring-cloud-config
          search-paths: respo
          username: codercyou
          password: xu616385173
  zipkin:
    base-url: http://localhost:9411
  #boot:
    #admin:
      #client:
        #url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info


